/**
 * Beacon New Rest Service Ver 1.0
 * Release notes:  `4.8`  * Add `onHold` to request body of endpoint `/submitOrder`
 *
 * OpenAPI spec version: release/4.8
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AddToCartItem } from './add-to-cart-item';
import { Shipping } from './shipping';

export interface AddItemsToOrderRequest {
    /**
     * The total amount of item to add to cart
     */
    addItemCount?: number;
    /**
     * The account id
     */
    accountId?: string;
    items?: Array<AddToCartItem>;
    shipping?: Shipping;
    apiSiteId?: string;
}
