import { AddressBookResponse } from './address-book-response';

export module AddressBookExamples {
    export const response1: AddressBookResponse = {
        result: null,
        addressBooks: [
            {
                addressBookInfo: {
                    country: 'United States',
                    lastName: '0506 test',
                    address2: '',
                    city: 'city2',
                    address1: 'address testing - pro 280381',
                    nickName: '0506 test',
                    postalCode: '90045',
                    stateValue: 'CA',
                    firstName: '',
                    phoneNumber: '6263396261',
                    state: 'California',
                    countryValue: 'USA',
                },
                accountName: '280381 (TEST DENVER)',
                accountLegacyId: '280381',
                addressBookId: '185115332',
            },
            {
                addressBookInfo: {
                    country: 'United States',
                    lastName: 'Lastname',
                    address2: 'Line 2',
                    city: 'Cityville',
                    address1: '1 Address Lane',
                    nickName: 'Test Address 1',
                    postalCode: '12345',
                    stateValue: 'VA',
                    firstName: 'Firstname',
                    phoneNumber: '0714841399',
                    state: 'Virginia',
                    countryValue: 'USA',
                },
                accountName: '280381 (TEST DENVER)',
                accountLegacyId: '280381',
                addressBookId: '193542260',
            },
            {
                addressBookInfo: {
                    country: 'United States',
                    lastName: 'Jones',
                    address2: '',
                    city: 'Testville',
                    address1: '1 Test Lane',
                    nickName: 'Test Address1',
                    postalCode: '12345',
                    stateValue: 'TN',
                    firstName: 'Bobby',
                    phoneNumber: '1234566789',
                    state: 'Tennessee',
                    countryValue: 'USA',
                },
                accountName: '280381 (TEST DENVER)',
                accountLegacyId: '280381',
                addressBookId: '196421891',
            },
            {
                addressBookInfo: {
                    country: 'United States',
                    lastName: 'Smart',
                    address2: '',
                    city: 'Delmar',
                    address1: '15518 Russell RD',
                    nickName: "Dad's door 2",
                    postalCode: '19940',
                    stateValue: 'DE',
                    firstName: 'Russell',
                    phoneNumber: '4104307505',
                    state: 'Delaware',
                    countryValue: 'USA',
                },
                accountName: '282976 (Russell Smart Home Improvement)',
                accountLegacyId: '282976',
                addressBookId: '13391606',
            },
            {
                addressBookInfo: {
                    country: 'United States',
                    lastName: 'Trachsel',
                    address2: '',
                    city: 'Aurora',
                    address1: '22724 E Long Dr',
                    nickName: 'PO# 2019-78',
                    postalCode: '80016-2075',
                    stateValue: 'CO',
                    firstName: 'Garry',
                    phoneNumber: '6514362274',
                    state: 'Colorado',
                    countryValue: 'USA',
                },
                accountName: '406008 (TERRA COTTA RESTORATION SVCS)',
                accountLegacyId: '406008',
                addressBookId: '124391036',
            },
            {
                addressBookInfo: {
                    country: 'United States',
                    lastName: 'test',
                    address2: '',
                    city: 'Mclean',
                    address1: '1933 Kennedy Drive',
                    nickName: '',
                    postalCode: '22102-1933',
                    stateValue: 'VA',
                    firstName: 'test',
                    phoneNumber: '1231231234',
                    state: 'Virginia',
                    countryValue: 'USA',
                },
                accountName: '372332 (POWER HOME REMODELING / NORTH)',
                accountLegacyId: '372332',
                addressBookId: '26281367',
            },
            {
                addressBookInfo: {
                    country: 'United States',
                    lastName: 'Garcia',
                    address2: '',
                    city: 'Austin',
                    address1: '3809 Eskew',
                    nickName: '',
                    postalCode: '78749',
                    stateValue: 'TX',
                    firstName: 'Vera',
                    phoneNumber: '5126806014',
                    state: 'Texas',
                    countryValue: 'USA',
                },
                accountName: '344700 (KAS Contracting Co.)',
                accountLegacyId: '344700',
                addressBookId: '20712009',
            },
        ],
        code: null,
        callBackParam: null,
        success: true,
        messageCode: null,
        messages: null,
    };
}
