/**
 * Beacon New Rest Service Ver 1.0
 * Release notes:  `4.8`  * Add `onHold` to request body of endpoint `/submitOrder`
 *
 * OpenAPI spec version: release/4.8
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */ import { DTAddressInfo } from './dt-address-info';
import { DTInfoPhotos } from './dt-info-photos';
import { DTLineItem } from './dt-line-item';

export interface DTInfo {
    statusStartDate?: string;
    status?: string;
    lastUpdated?: string;
    timeArrived?: string;
    custPO?: string;
    type?: string;
    destination?: DTAddressInfo;
    projectedCompletedDate?: string;
    latestRequestedDelivery?: string;
    photos?: Array<DTInfoPhotos>;
    orderNo?: string;
    projectedArrivalDate?: string;
    parentOrderNo?: string;
    statusDateTimeMessage?: string;
    earliestRequestedDelivery?: string;
    driver?: string;
    lines?: Array<DTLineItem>;
    orgin?: DTAddressInfo;
    statusEndDate?: string;
}
