/**
 * Beacon New Rest Service Ver 1.0
 * Release notes:  `4.8`  * Add `onHold` to request body of endpoint `/submitOrder`
 *
 * OpenAPI spec version: release/4.8
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface HoverAttributes {
    sellingUom?: string;
    piecesPerUom?: string;
    coverageUom?: string;
    ppCoverageUom?: string;
    lengthExposure?: string;
    widthExposure?: string;
    lengthHover?: string;
    widthHover?: string;
    ncpSellingUom?: string;
    gcpSellingUom?: string;
    sslvoDimensionIn?: string;
    sswhoDimensionOption1In?: string;
    sswhoDimensionOption2In?: string;
    sswhoDimensionOption3In?: string;
    lslvoDimensionIn?: string;
    lswhoDimensionIn?: string;
    rvlvoDimensionIn?: string;
    rvwhoDimensionIn?: string;
    nfvaHover?: string;
    nfvaUomHover?: string;
    fhLapIn?: string;
    fvLapIn?: string;
    chLapIn?: string;
    cvLapIn?: string;
    cfmValue?: string;
    cfmUom?: string;
}
