/**
 * Beacon New Rest Service Ver 1.0
 * Release notes:  `4.8`  * Add `onHold` to request body of endpoint `/submitOrder`
 *
 * OpenAPI spec version: release/4.8
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface OrderHistoryLineItemV1 {
    specialInstructions?: string;
    productOrItemNumber?: string;
    subTotal?: number;
    itemOrProductDescription?: string;
    unitPrice?: number;
    quantity: number;
    itemNumber: string;
    unitOfMeasure: string;
    productImageUrl?: string;
}

export interface OrderHistoryLineItemV2 {
    specialInstructions: string;
    productOrItemNumber: string;
    subTotal: 0;
    subTotalNull: true;
    itemOrProductDescription: string;
    unitPrice: 0;
    unitPriceNull: true;
    quantity: 0;
    itemNumber: string;
    unitOfMeasure: string;
    unitOfMeasureDisplay: string;
    productImageUrl: string;
    productOnErrorImageUrl: string;
    productId: string;
    PDPUrl: string;
    skuPDPDisplayTitle: string;
    displayQuantityMsg: true;
    quantityMsg: string;
    orderQuantity?: number;
    shipQuantity?: number;
}
