/**
 * Beacon New Rest Service Ver 1.0
 * Release notes:  `4.8`  * Add `onHold` to request body of endpoint `/submitOrder`
 *
 * OpenAPI spec version: release/4.8
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ImageUrl } from './image-url';
import { VariationType } from './variation-type';

export interface TemplateListItem {
    templateItemId?: string;
    productImageUrl?: string;
    productOnErrorImageUrl?: string;
    itemOrProductDescription?: string;
    itemNumber?: string;
    productOrItemNumber?: string;
    internalProductName?: string;
    currentVariation?: VariationType;
    variations?: Array<VariationType>;
    unitPrice?: number;
    unitOfMeasure?: string;
    quantity?: number;
    available?: boolean;
    imageUrl?: ImageUrl;
}
